version: '3.8'

services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
      target: fula-pack
    working_dir: /opt/fula/apps/box
    command: rushx start


  react-gallery:
    build:
      context: .
      dockerfile: Dockerfile
      target: examples
      args:
        EXAMPLE_PATH: /opt/fula/examples/gallery/simple/react-app
    ports:
      - 3000:3000
    depends_on:
      - box

  react-todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: examples
      args:
        EXAMPLE_PATH: /opt/fula/examples/react-todo-app
    volumes:
      - ./examples/react-todo-app/src:/opt/fula/examples/react-todo-app/src
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - box
