version: '3'

services:
  box:
    build:
      dockerfile: ./Dockerfile.box
    network_mode: 'host'
    working_dir: /opt/box
    command: npm start
    volumes:
      - ./apps/box/src:/opt/box/src
