name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./apps/box/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/box:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/box:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/box:buildcache,mode=max 
